### ISSUE TITLE
Add links to next read below pages for readers to continue reading

### ISSUE THREAD

**Issue by phenax** [phenax/algebraic-effects#12]
Add simple links at the bottom of each page to allow readers to continue reading

```
< Previous                                 Next >
Core modules              Generic effects
```

**Comment by ayoola-solomon** [comment]
I will pick this up

**Comment by phenax** [comment]
@ayoola-solomon Go right ahead! If you need any help with it, you can tag me here.

**Comment by ayoola-solomon** [comment]
@phenax what do you think about this ?
<img width="916" alt="Screenshot 2019-10-03 at 11 24 12" src="https://user-images.githubusercontent.com/7336593/66115071-657a8f80-e5d0-11e9-8200-6d322fe02349.png">

**Comment by phenax** [comment]
@ayoola-solomon Nice!

**Comment by ayoola-solomon** [comment]
@phenax here is the PR to the docs update #25
